USE [master]
GO

/****** Object:  Database [careers]    Script Date: 01/28/2012 07:42:18 ******/
CREATE DATABASE [careers] ON  PRIMARY 
( NAME = N'careers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\careers.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'careers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\careers_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [careers] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [careers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [careers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [careers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [careers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [careers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [careers] SET ARITHABORT OFF 
GO

ALTER DATABASE [careers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [careers] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [careers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [careers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [careers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [careers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [careers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [careers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [careers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [careers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [careers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [careers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [careers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [careers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [careers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [careers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [careers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [careers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [careers] SET  READ_WRITE 
GO

ALTER DATABASE [careers] SET RECOVERY FULL 
GO

ALTER DATABASE [careers] SET  MULTI_USER 
GO

ALTER DATABASE [careers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [careers] SET DB_CHAINING OFF 
GO


